version: '2'
services:
 transmission:
  image: kinga0879/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/aking/media/video/:/data
    - /home/aking/transmission/expressvpn_dc.ovpn:/etc/openvpn/custom/expressvpn_dc.ovpn
    - /home/aking/transmission/password.ovpn:/etc/openvpn/custom/password.ovpn
  environment:
    - OPENVPN_CONFIG=expressvpn_dc
    - OPENVPN_PROVIDER=CUSTOM
    - OPENVPN_USERNAME=8vtllggs3zcjw1mn3kml632w
    - OPENVPN_PASSWORD=ufqatp2v6vjp4imslohit3ap
    - LOCAL_NETWORK=10.0.1.0/24
    - PUID=1000
    - PGID=1000

 proxy:
  image: haugene/transmission-openvpn-proxy
  links:
    - transmission
  ports:
    - 8080:8080
  volumes:
    - /etc/localtime:/etc/localtime:ro
